# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

output:
  formats:
    - format: colored-line-number

# Settings for enabling and disabling linters
linters:
  disable-all: true
  enable:
    - contextcheck
    - dupword
    - errcheck
    - errchkjson
    - gci
    - godot
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - loggercheck
    - mirror
    - musttag
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - reassign
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

# Settings of specific linters
linters-settings:
  gci:
    # gci is flexible alternative to goimports.
    # To auto-fix imports, run `golangci-lint run --disable-all --enable=gci --fix`.
    sections:
      - standard
      - default
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 130